-- Arquivo mantido apenas por compatibilidade com a primeira versão.
-- A estrutura vigente está dividida e documentada em supabase/queries.
-- Execute os arquivos numerados daquela pasta, em ordem, em um banco novo.
