"use client";

import { useMemo, useState } from "react";
import { Icon } from "../icons";
import type { InventoryItem, ProjectIssue, ReportSummary, Task } from "../types";
import { Modal } from "../ui";
import { buildAutomaticAttention } from "../attention-data";

type Props = {
  tasks: Task[];
  inventory: InventoryItem[];
  reports: ReportSummary[];
  issues: ProjectIssue[];
  saveIssue: (issue: ProjectIssue) => Promise<void>;
};

export function Alerts({ tasks, inventory, reports, issues, saveIssue }: Props) {
  const [creating,setCreating]=useState(false);
  const [processing,setProcessing]=useState(false);
  const notifications=useMemo(()=>buildAutomaticAttention(tasks,inventory,reports),[inventory,reports,tasks]);
  const openIssues=issues.filter((issue)=>issue.status!=="resolved");
  return <div className="view-stack alerts-view"><section className="attention-hero glass"><div><span className="overline">CENTRAL DE ATENÇÃO</span><h2>{notifications.length+openIssues.length} pontos pedem acompanhamento</h2><p>O sistema cruza cronograma, estoque, relatórios e registros manuais para antecipar impactos.</p></div><button className="primary-btn" onClick={()=>setCreating(true)}><Icon name="plus"/> Registrar ocorrência</button></section><div className="attention-layout"><section className="panel glass"><div className="panel-header"><div><span className="overline">ALERTAS AUTOMÁTICOS</span><h3>Detectados pelo Em Dia</h3></div><span className="notification-count">{notifications.length}</span></div><div className="attention-list">{notifications.length?notifications.map((item)=><article className={`attention-item ${item.tone}`} key={item.id}><span><Icon name="alert"/></span><div><small>{item.kind}</small><strong>{item.title}</strong><p>{item.detail}</p></div></article>):<div className="attention-empty"><Icon name="check"/><strong>Nenhum alerta automático</strong><small>Cronograma, relatórios e estoque estão em ordem.</small></div>}</div></section><section className="panel glass"><div className="panel-header"><div><span className="overline">PONTOS DE ATENÇÃO</span><h3>Registrados pela equipe</h3></div><span className="notification-count">{openIssues.length}</span></div><div className="attention-list">{openIssues.map((issue)=><article className={`attention-item ${issue.priority}`} key={issue.id}><span><Icon name="alert"/></span><div><small>{issue.category} · {issue.priority}</small><strong>{issue.title}</strong><p>{issue.description}</p>{issue.taskId&&<em>{tasks.find((task)=>task.id===issue.taskId)?.code} · {tasks.find((task)=>task.id===issue.taskId)?.name}</em>}</div><button className="secondary-btn compact" disabled={processing} onClick={async()=>{setProcessing(true);try{await saveIssue({...issue,status:"resolved"})}finally{setProcessing(false)}}}>Resolver</button></article>)}</div></section></div>{creating&&<IssueForm tasks={tasks} processing={processing} onClose={()=>setCreating(false)} onSave={async(issue)=>{setProcessing(true);try{await saveIssue(issue);setCreating(false)}finally{setProcessing(false)}}}/>}</div>;
}

function IssueForm({tasks,processing,onClose,onSave}:{tasks:Task[];processing:boolean;onClose:()=>void;onSave:(issue:ProjectIssue)=>Promise<void>}) { const [issue,setIssue]=useState<ProjectIssue>({id:"",title:"",description:"",category:"field",priority:"medium",status:"open",createdAt:new Date().toISOString()}); return <Modal title="Registrar ponto de atenção" subtitle="Relacione a ocorrência ao planejamento quando houver impacto no prazo." onClose={onClose}><form className="invite-form" onSubmit={(e)=>{e.preventDefault();void onSave(issue)}}><label><span>Título</span><input required value={issue.title} onChange={(e)=>setIssue({...issue,title:e.target.value})}/></label><label><span>Descrição</span><textarea required rows={4} value={issue.description} onChange={(e)=>setIssue({...issue,description:e.target.value})}/></label><div className="form-grid"><label><span>Categoria</span><select value={issue.category} onChange={(e)=>setIssue({...issue,category:e.target.value as ProjectIssue["category"]})}><option value="field">Campo</option><option value="schedule">Cronograma</option><option value="stock">Estoque</option><option value="quality">Qualidade</option><option value="safety">Segurança</option><option value="other">Outro</option></select></label><label><span>Prioridade</span><select value={issue.priority} onChange={(e)=>setIssue({...issue,priority:e.target.value as ProjectIssue["priority"]})}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label></div><label><span>Atividade afetada</span><select value={issue.taskId??""} onChange={(e)=>setIssue({...issue,taskId:e.target.value||undefined})}><option value="">Sem vínculo</option>{tasks.map((task)=><option value={task.id} key={task.id}>{task.code} · {task.name}</option>)}</select></label><label><span>Prazo para solução</span><input type="date" value={issue.dueDate??""} onChange={(e)=>setIssue({...issue,dueDate:e.target.value||undefined})}/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancelar</button><button className="primary-btn" disabled={processing}>{processing?<><span className="button-spinner"/>Salvando...</>:"Registrar ocorrência"}</button></div></form></Modal> }
