"use client";

import { useMemo, useState } from "react";
import { Icon } from "../icons";
import type { InventoryItem, Task } from "../types";
import { Modal } from "../ui";

type Props = {
  items: InventoryItem[];
  tasks: Task[];
  saveItem: (item: InventoryItem) => Promise<void>;
  moveItem: (itemId: string, type: "entry" | "exit" | "adjustment", quantity: number, taskId?: string, note?: string) => Promise<void>;
  deleteItem: (item: InventoryItem) => Promise<void>;
};

const remainingDemand = (item: InventoryItem) => item.allocations.reduce((sum, allocation) => sum + Math.max(0, allocation.planned - allocation.consumed), 0);
export function Inventory({ items, tasks, saveItem, moveItem, deleteItem }: Props) {
  const [editing, setEditing] = useState<InventoryItem | null>(null);
  const [moving, setMoving] = useState<InventoryItem | null>(null);
  const [search, setSearch] = useState("");
  const [processing, setProcessing] = useState(false);
  const filtered = useMemo(() => items.filter((item) => `${item.name} ${item.category} ${item.sku ?? ""}`.toLowerCase().includes(search.toLowerCase())), [items, search]);
  const shortage = items.filter((item) => item.quantity < remainingDemand(item) || item.quantity <= item.minimum);
  return <div className="view-stack inventory-view">
    <section className="inventory-summary glass"><div><span className="overline">MATERIAIS DA OBRA</span><h2>Estoque conectado ao planejamento</h2><p>Reserve materiais por EAP e antecipe faltas antes que afetem o cronograma.</p></div><div className="inventory-kpis"><span><b>{items.length}</b> itens</span><span className={shortage.length ? "danger" : ""}><b>{shortage.length}</b> alertas</span><span><b>{items.reduce((sum, item) => sum + item.allocations.length, 0)}</b> vínculos EAP</span></div><button className="primary-btn" onClick={() => setEditing({ id:"", name:"", category:"Geral", unit:"un", quantity:0, minimum:0, leadDays:0, allocations:[] })}><Icon name="plus"/> Novo material</button></section>
    <section className="panel glass"><div className="panel-header"><div><span className="overline">POSIÇÃO ATUAL</span><h3>Materiais e reservas</h3></div><label className="search-box"><Icon name="search"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar material..."/></label></div>
      <div className="inventory-table"><div className="inventory-row inventory-head"><span>Material</span><span>Saldo</span><span>Reservado</span><span>Disponível</span><span>Situação</span><span/></div>{filtered.map((item) => { const demand=remainingDemand(item); const available=item.quantity-demand; const state=item.quantity <= item.minimum ? "Mínimo atingido" : available < 0 ? "Reposição necessária" : "Abastecido"; return <div className="inventory-row" key={item.id}><span><strong>{item.name}</strong><small>{item.category}{item.sku ? ` · ${item.sku}` : ""}</small></span><b>{item.quantity} {item.unit}</b><b>{demand} {item.unit}</b><b className={available < 0 ? "danger" : ""}>{available} {item.unit}</b><em className={state === "Abastecido" ? "ok" : "warning"}>{state}</em><span className="inventory-actions"><button className="secondary-btn compact" onClick={() => setMoving(item)}>Movimentar</button><button className="icon-btn tiny" onClick={() => setEditing(item)}><Icon name="settings"/></button></span></div>; })}</div>
    </section>
    {editing && <InventoryForm item={editing} tasks={tasks} processing={processing} onClose={() => setEditing(null)} onDelete={editing.id ? async () => { setProcessing(true); try { await deleteItem(editing); setEditing(null); } finally { setProcessing(false); } } : undefined} onSave={async (item) => { setProcessing(true); try { await saveItem(item); setEditing(null); } finally { setProcessing(false); } }}/>} 
    {moving && <MovementForm item={moving} tasks={tasks} processing={processing} onClose={() => setMoving(null)} onSave={async (type,quantity,taskId,note) => { setProcessing(true); try { await moveItem(moving.id,type,quantity,taskId,note); setMoving(null); } finally { setProcessing(false); } }}/>} 
  </div>;
}

function InventoryForm({ item, tasks, processing, onClose, onSave, onDelete }: { item:InventoryItem; tasks:Task[]; processing:boolean; onClose:()=>void; onSave:(item:InventoryItem)=>Promise<void>; onDelete?:()=>Promise<void> }) {
  const [value,setValue]=useState(item);
  const executable=tasks.filter((task)=>!tasks.some((child)=>child.parentId===task.id));
  return <Modal title={item.id ? "Editar material" : "Cadastrar material"} subtitle="Defina o saldo mínimo e a necessidade prevista por EAP." onClose={onClose} wide><form className="inventory-form" onSubmit={(event)=>{event.preventDefault(); void onSave(value);}}><label><span>Material</span><input required value={value.name} onChange={(e)=>setValue({...value,name:e.target.value})}/></label><label><span>Categoria</span><input required value={value.category} onChange={(e)=>setValue({...value,category:e.target.value})}/></label><label><span>Código / SKU</span><input value={value.sku??""} onChange={(e)=>setValue({...value,sku:e.target.value})}/></label><label><span>Unidade</span><input required value={value.unit} onChange={(e)=>setValue({...value,unit:e.target.value})}/></label><label><span>Saldo atual</span><input type="number" min="0" step="0.001" value={value.quantity} onChange={(e)=>setValue({...value,quantity:Number(e.target.value)})}/></label><label><span>Estoque mínimo</span><input type="number" min="0" step="0.001" value={value.minimum} onChange={(e)=>setValue({...value,minimum:Number(e.target.value)})}/></label><label><span>Prazo de reposição (dias)</span><input type="number" min="0" value={value.leadDays} onChange={(e)=>setValue({...value,leadDays:Number(e.target.value)})}/></label><section className="allocation-editor full"><header><div><span>RESERVAS POR EAP</span><p>Informe quanto deste material está previsto para cada atividade.</p></div></header>{value.allocations.map((allocation,index)=><div key={allocation.id||index}><select value={allocation.taskId} onChange={(e)=>setValue({...value,allocations:value.allocations.map((a,i)=>i===index?{...a,taskId:e.target.value}:a)})}>{executable.map((task)=><option value={task.id} key={task.id}>{task.code} · {task.name}</option>)}</select><input aria-label="Quantidade planejada" type="number" min="0.001" step="0.001" value={allocation.planned} onChange={(e)=>setValue({...value,allocations:value.allocations.map((a,i)=>i===index?{...a,planned:Number(e.target.value)}:a)})}/><button type="button" className="icon-btn tiny" onClick={()=>setValue({...value,allocations:value.allocations.filter((_,i)=>i!==index)})}><Icon name="close"/></button></div>)}<button type="button" className="text-btn" disabled={!executable.length} onClick={()=>setValue({...value,allocations:[...value.allocations,{id:"",taskId:executable[0].id,planned:1,consumed:0}]})}><Icon name="plus"/> Vincular EAP</button></section><div className="modal-actions full">{onDelete&&<button type="button" className="danger-btn" disabled={processing} onClick={()=>void onDelete()}>Excluir</button>}<span/><button type="button" className="secondary-btn" onClick={onClose}>Cancelar</button><button className="primary-btn" disabled={processing}>{processing?<><span className="button-spinner"/>Salvando...</>:"Salvar material"}</button></div></form></Modal>;
}

function MovementForm({ item,tasks,processing,onClose,onSave }:{item:InventoryItem;tasks:Task[];processing:boolean;onClose:()=>void;onSave:(type:"entry"|"exit"|"adjustment",quantity:number,taskId?:string,note?:string)=>Promise<void>}) { const [type,setType]=useState<"entry"|"exit"|"adjustment">("entry"); const [quantity,setQuantity]=useState(1); const [taskId,setTaskId]=useState(""); const [note,setNote]=useState(""); return <Modal title={`Movimentar · ${item.name}`} subtitle={`Saldo atual: ${item.quantity} ${item.unit}`} onClose={onClose}><form className="invite-form" onSubmit={(e)=>{e.preventDefault();void onSave(type,quantity,taskId||undefined,note||undefined)}}><label><span>Operação</span><select value={type} onChange={(e)=>setType(e.target.value as typeof type)}><option value="entry">Entrada</option><option value="exit">Saída / consumo</option><option value="adjustment">Ajustar saldo para</option></select></label><label><span>{type==="adjustment"?"Novo saldo":"Quantidade"}</span><input required type="number" min={type==="adjustment"?0:0.001} step="0.001" value={quantity} onChange={(e)=>setQuantity(Number(e.target.value))}/></label>{type==="exit"&&<label><span>Consumido na EAP</span><select value={taskId} onChange={(e)=>setTaskId(e.target.value)}><option value="">Sem vínculo específico</option>{tasks.map((task)=><option value={task.id} key={task.id}>{task.code} · {task.name}</option>)}</select></label>}<label><span>Observação</span><textarea rows={3} value={note} onChange={(e)=>setNote(e.target.value)}/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancelar</button><button className="primary-btn" disabled={processing}>{processing?<><span className="button-spinner"/>Processando...</>:"Confirmar movimentação"}</button></div></form></Modal> }
